name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMjJjZTIxZTgtYzViMC00MDNlLWJkMzctY2RhZmY5ZTcxNGUxIiwidGVuYW50X2lkIjoiMTcxM2VlMmI3NTQ3MDY0ZDg5ZWM4NDE1MDM4MjU1ZGQyNDY2ZDk4MzkyZDRhZmE4ZjZmNGQ0ODM1ZjI0NzA3ZCIsImludGVybmFsX3NlY3JldCI6IjcxZTc5YjhhLTAyYTUtNDUwNC1iMDIwLWQ0ZWQ3NzQ1ZjA0NiJ9.p9SN6ck1w6l81xiGNlNAn0xtrWTGUIIc4JxN4ZSXlsQ"
JWT_SECRET = "mysupersecret"
MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"